//! Newtype wrappers for the various string IDs that flow through
//! jmapsync.
//!
//! Without these, an opaque server `Email.id`, a maildir basename,
//! and a parsed RFC 5322 `Message-ID` are all the same `String` type
//! and the compiler can't tell when one slot accidentally takes the
//! wrong kind. With them, the type system catches swaps at the
//! boundary and call-sites stay readable thanks to `AsRef<str>` /
//! `Display` and the rusqlite glue below.
//!
//! Each newtype is generated by `define_id_newtype!` so the trait
//! surface stays uniform: add a new ID kind by adding one line at
//! the bottom of this file.

use rusqlite::ToSql;
use rusqlite::types::{FromSql, FromSqlResult, ToSqlOutput, ValueRef};
use serde::{Deserialize, Serialize};
use std::borrow::Borrow;
use std::fmt;

/// Emit the standard impl set for a `String`-backed ID newtype:
/// derives + `Display` + `AsRef<str>` + `From<String>` /
/// `From<&str>` + `From<&Self> for String` (so jmap-client's
/// `impl Into<String>` slots accept a borrowed id) +
/// `rusqlite::ToSql` / `FromSql` (so SQL `params!` and `row.get`
/// continue to work) + serde transparent.
macro_rules! define_id_newtype {
    ($name:ident) => {
        #[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
        #[serde(transparent)]
        pub struct $name(String);

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str(&self.0)
            }
        }

        impl AsRef<str> for $name {
            fn as_ref(&self) -> &str {
                &self.0
            }
        }

        // `Borrow<str>` lets `HashMap<$name, V>::get(s: &str)` work
        // without allocating a fresh newtype at every lookup. Safe
        // because the derived `Hash` and `Eq` delegate straight to
        // the inner `String`, whose impls already match `str`.
        impl Borrow<str> for $name {
            fn borrow(&self) -> &str {
                &self.0
            }
        }

        impl From<String> for $name {
            fn from(s: String) -> Self {
                Self(s)
            }
        }

        impl From<&str> for $name {
            fn from(s: &str) -> Self {
                Self(s.to_string())
            }
        }

        impl From<$name> for String {
            fn from(id: $name) -> Self {
                id.0
            }
        }

        impl From<&$name> for String {
            fn from(id: &$name) -> Self {
                id.0.clone()
            }
        }

        impl ToSql for $name {
            fn to_sql(&self) -> rusqlite::Result<ToSqlOutput<'_>> {
                Ok(ToSqlOutput::from(self.0.as_str()))
            }
        }

        impl FromSql for $name {
            fn column_result(value: ValueRef<'_>) -> FromSqlResult<Self> {
                String::column_result(value).map(Self)
            }
        }
    };
}

// Server-opaque JMAP ids.
define_id_newtype!(JmapEmailId);
define_id_newtype!(JmapMailboxId);
define_id_newtype!(JmapBlobId);
define_id_newtype!(JmapThreadId);
define_id_newtype!(JmapAccountId);

// Local-side ids.
define_id_newtype!(MaildirId);

// Parsed RFC 5322 Message-ID, angle brackets stripped.
define_id_newtype!(MessageId);

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn display_and_as_ref_yield_inner_str() {
        let id = JmapEmailId::from("abc-123");
        assert_eq!(format!("{}", id), "abc-123");
        assert_eq!(id.as_ref(), "abc-123");
    }

    #[test]
    fn from_owned_and_borrowed_string() {
        let owned = JmapEmailId::from("abc".to_string());
        let borrowed = JmapEmailId::from("abc");
        assert_eq!(owned, borrowed);
    }

    #[test]
    fn into_string_borrowed_and_owned() {
        let id = JmapEmailId::from("abc");
        let s_borrowed: String = (&id).into();
        assert_eq!(s_borrowed, "abc");
        let s_owned: String = id.into();
        assert_eq!(s_owned, "abc");
    }

    #[test]
    fn equality_and_hash_within_type() {
        let a = MaildirId::from("x.eml");
        let b = MaildirId::from("x.eml");
        let mut set = HashSet::new();
        set.insert(a);
        assert!(set.contains(&b));
    }

    #[test]
    fn rusqlite_roundtrip() {
        use rusqlite::{Connection, params};
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch("CREATE TABLE t (id TEXT)").unwrap();
        let id = JmapEmailId::from("test-id");
        conn.execute("INSERT INTO t (id) VALUES (?1)", params![id])
            .unwrap();
        let got: JmapEmailId = conn
            .query_row("SELECT id FROM t", [], |r| r.get(0))
            .unwrap();
        assert_eq!(got, id);
    }

    #[test]
    fn serde_is_transparent() {
        let id = MessageId::from("01234@example.com");
        let s = serde_json::to_string(&id).unwrap();
        assert_eq!(s, r#""01234@example.com""#);
        let back: MessageId = serde_json::from_str(&s).unwrap();
        assert_eq!(back, id);
    }
}
